################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
C_SRCS := 
OBJ_SRCS := 
O_SRCS := 
S_SRCS := 
S_UPPER_SRCS := 
C_DEPS := 
EXECUTABLES := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
PowerModules/System_Service/cfg \
PowerModules/System_Service/src \
SoftwareModules/Ambient_Light_Sensor/cfg \
SoftwareModules/Ambient_Light_Sensor/src \
SoftwareModules/Averege_Speed/cfg \
SoftwareModules/Averege_Speed/src \
SoftwareModules/BLE_Call_Module/cfg \
SoftwareModules/BLE_Call_Module/src \
SoftwareModules/BLE_Music_module/cfg \
SoftwareModules/BLE_Music_module/src \
SoftwareModules/Button_Manager/cfg \
SoftwareModules/Button_Manager/src \
SoftwareModules/CanStack/cfg \
SoftwareModules/CanStack/src \
SoftwareModules/Dio/cfg \
SoftwareModules/Dio/src \
SoftwareModules/Fuel_Guage/cfg \
SoftwareModules/Fuel_Guage/src \
SoftwareModules/Gear_Position/Cfg \
SoftwareModules/Gear_Position/Src \
SoftwareModules/I2C_Handler/cfg \
SoftwareModules/I2C_Handler/src \
SoftwareModules/NVM_Handler/cfg \
SoftwareModules/NVM_Handler/src \
SoftwareModules/Odometer/cfg \
SoftwareModules/Odometer/src \
SoftwareModules/Os/src \
SoftwareModules/RTC/cfg \
SoftwareModules/RTC/src \
SoftwareModules/Service_Remainder/cfg \
SoftwareModules/Service_Remainder/src \
SoftwareModules/Side_Stand_TT/src \
SoftwareModules/Speedometer/cfg \
SoftwareModules/Speedometer/src \
SoftwareModules/TFT_Illumination/cfg \
SoftwareModules/TFT_Illumination/src \
SoftwareModules/Tachometer/cfg \
SoftwareModules/Tachometer/src \
SoftwareModules/Telltale/Abs_Telltale/cfg \
SoftwareModules/Telltale/Abs_Telltale/src \
SoftwareModules/Telltale/TTMgr/cfg \
SoftwareModules/Telltale/TTMgr/src \
SoftwareModules/Telltale/Tell_Tale_Fog_Lamp/cfg \
SoftwareModules/Telltale/Tell_Tale_Fog_Lamp/src \
SoftwareModules/Telltale/Tell_Tale_MIL/cfg \
SoftwareModules/Telltale/Tell_Tale_MIL/src \
SoftwareModules/Telltale/Tell_Tale_Oil_Pressure/cfg \
SoftwareModules/Telltale/Tell_Tale_Oil_Pressure/src \
SoftwareModules/Tft_Derating/cfg \
SoftwareModules/Tft_Derating/src \
SoftwareModules/Trip_Computer/src \
SoftwareModules/Trip_Timer/cfg \
SoftwareModules/Trip_Timer/src \
SoftwareModules/UART_IMXRT_DATAMANAGER/UART/src \
SoftwareModules/UDS/Cfg \
SoftwareModules/UDS/Src \
SoftwareModules/Voltage\ Battery\ Status/cfg \
SoftwareModules/Voltage\ Battery\ Status/src \
board \
component/lists \
component/serial_manager \
component/uart \
custom \
device \
drivers \
freertos/freertos_kernel \
freertos/freertos_kernel/portable/GCC/ARM_CM4F \
freertos/freertos_kernel/portable/MemMang \
gen \
gen/guider_fonts \
gen/images \
lvgl/demos/benchmark/assets \
lvgl/demos/benchmark \
lvgl/demos/keypad_encoder \
lvgl/demos/music/assets \
lvgl/demos/music \
lvgl/demos/stress \
lvgl/demos/widgets/assets \
lvgl/demos/widgets \
lvgl/src/core \
lvgl/src/draw/arm2d \
lvgl/src/draw \
lvgl/src/draw/nxp_pxp \
lvgl/src/draw/nxp_vglite \
lvgl/src/draw/sdl \
lvgl/src/draw/stm32_dma2d \
lvgl/src/draw/sw \
lvgl/src/extra/layouts/flex \
lvgl/src/extra/layouts/grid \
lvgl/src/extra/libs/bmp \
lvgl/src/extra/libs/ffmpeg \
lvgl/src/extra/libs/freetype \
lvgl/src/extra/libs/fsdrv \
lvgl/src/extra/libs/gif \
lvgl/src/extra/libs/png \
lvgl/src/extra/libs/qrcode \
lvgl/src/extra/libs/rlottie \
lvgl/src/extra/libs/sjpg \
lvgl/src/extra \
lvgl/src/extra/others/fragment \
lvgl/src/extra/others/gridnav \
lvgl/src/extra/others/imgfont \
lvgl/src/extra/others/monkey \
lvgl/src/extra/others/snapshot \
lvgl/src/extra/themes/basic \
lvgl/src/extra/themes/default \
lvgl/src/extra/themes/mono \
lvgl/src/extra/widgets/animimg \
lvgl/src/extra/widgets/calendar \
lvgl/src/extra/widgets/chart \
lvgl/src/extra/widgets/colorwheel \
lvgl/src/extra/widgets/imgbtn \
lvgl/src/extra/widgets/keyboard \
lvgl/src/extra/widgets/led \
lvgl/src/extra/widgets/list \
lvgl/src/extra/widgets/menu \
lvgl/src/extra/widgets/meter \
lvgl/src/extra/widgets/msgbox \
lvgl/src/extra/widgets/span \
lvgl/src/extra/widgets/spinbox \
lvgl/src/extra/widgets/spinner \
lvgl/src/extra/widgets/tabview \
lvgl/src/extra/widgets/tileview \
lvgl/src/extra/widgets/win \
lvgl/src/font \
lvgl/src/hal \
lvgl/src/misc \
lvgl/src/widgets \
lvgl/vglite/VGLite/rtos \
lvgl/vglite/VGLite \
lvgl/vglite/VGLiteKernel/rtos \
lvgl/vglite/VGLiteKernel \
lvgl/vglite/elementary/src \
lvgl/vglite/font \
lvgl/vglite/font/mcufont/decoder \
source \
startup \
utilities \
xip \

