/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define BOARD_INITPINS_IOMUXC_GPR_GPR43_GPIO_MUX3_GPIO_SEL_HIGH_MASK 0x40U /*!< GPIO3 and CM7_GPIO3 share same IO MUX function, GPIO_MUX3 selects one GPIO function: affected bits mask */

/* GPIO_DISP_B1_00 (coord E13), ENET_RGMII_RX_EN */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RGMII_RX_EN_PERIPHERAL                         LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RGMII_RX_EN_SIGNAL                         lcdif_clk   /*!< Signal name */

/* GPIO_DISP_B1_04 (coord E10), ENET_RGMII_RXD2 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RGMII_RXD2_PERIPHERAL                          LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RGMII_RXD2_SIGNAL                         lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RGMII_RXD2_CHANNEL                                0U   /*!< Signal channel */

/* GPIO_DISP_B1_05 (coord C11), ENET_RGMII_RXD3 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RGMII_RXD3_PERIPHERAL                          LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RGMII_RXD3_SIGNAL                         lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RGMII_RXD3_CHANNEL                                1U   /*!< Signal channel */

/* GPIO_DISP_B1_06 (coord D10), ENET_RGMII_TXD3 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RGMII_TXD3_PERIPHERAL                          LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RGMII_TXD3_SIGNAL                         lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RGMII_TXD3_CHANNEL                                2U   /*!< Signal channel */

/* GPIO_DISP_B1_07 (coord E12), ENET_RGMII_TXD2 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RGMII_TXD2_PERIPHERAL                          LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RGMII_TXD2_SIGNAL                         lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RGMII_TXD2_CHANNEL                                3U   /*!< Signal channel */

/* GPIO_DISP_B1_08 (coord A15), ENET_RGMII_TXD1 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RGMII_TXD1_PERIPHERAL                          LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RGMII_TXD1_SIGNAL                         lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RGMII_TXD1_CHANNEL                                4U   /*!< Signal channel */

/* GPIO_DISP_B1_09 (coord C13), ENET_RGMII_TXD0 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RGMII_TXD0_PERIPHERAL                          LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RGMII_TXD0_SIGNAL                         lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RGMII_TXD0_CHANNEL                                5U   /*!< Signal channel */

/* GPIO_DISP_B1_10 (coord B14), ENET_RGMII_TX_EN */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RGMII_TX_EN_PERIPHERAL                         LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RGMII_TX_EN_SIGNAL                        lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RGMII_TX_EN_CHANNEL                               6U   /*!< Signal channel */

/* GPIO_DISP_B1_11 (coord A14), ENET_RGMII_TXC */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RGMII_TXC_PERIPHERAL                           LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RGMII_TXC_SIGNAL                          lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RGMII_TXC_CHANNEL                                 7U   /*!< Signal channel */

/* GPIO_DISP_B2_02 (coord E9), ENET_TXD0 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TXD0_PERIPHERAL                                LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TXD0_SIGNAL                               lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_TXD0_CHANNEL                                     10U   /*!< Signal channel */

/* GPIO_DISP_B2_03 (coord D7), ENET_TXD1 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TXD1_PERIPHERAL                                LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TXD1_SIGNAL                               lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_TXD1_CHANNEL                                     11U   /*!< Signal channel */

/* GPIO_DISP_B2_04 (coord C7), ENET_TXEN */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TXEN_PERIPHERAL                                LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TXEN_SIGNAL                               lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_TXEN_CHANNEL                                     12U   /*!< Signal channel */

/* GPIO_DISP_B2_05 (coord C9), ENET_TX_REF_CLK */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TX_REF_CLK_PERIPHERAL                          LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TX_REF_CLK_SIGNAL                         lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_TX_REF_CLK_CHANNEL                               13U   /*!< Signal channel */

/* GPIO_DISP_B2_06 (coord C6), ENET_RXD0 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RXD0_PERIPHERAL                                LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RXD0_SIGNAL                               lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RXD0_CHANNEL                                     14U   /*!< Signal channel */

/* GPIO_DISP_B2_07 (coord D6), ENET_RXD1 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RXD1_PERIPHERAL                                LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RXD1_SIGNAL                               lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RXD1_CHANNEL                                     15U   /*!< Signal channel */

/* GPIO_DISP_B2_08 (coord B5), ENET_CRS_DV */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_CRS_DV_PERIPHERAL                              LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_CRS_DV_SIGNAL                             lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_CRS_DV_CHANNEL                                   16U   /*!< Signal channel */

/* GPIO_DISP_B2_09 (coord D8), ENET_RXER */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RXER_PERIPHERAL                                LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RXER_SIGNAL                               lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RXER_CHANNEL                                     17U   /*!< Signal channel */

/* GPIO_DISP_B2_10 (coord D9), BT_UART_TXD */
/* Routed pin properties */
#define BOARD_INITPINS_BT_UART_TXD_PERIPHERAL                              LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_BT_UART_TXD_SIGNAL                             lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_BT_UART_TXD_CHANNEL                                   18U   /*!< Signal channel */

/* GPIO_DISP_B2_11 (coord A6), BT_UART_RXD */
/* Routed pin properties */
#define BOARD_INITPINS_BT_UART_RXD_PERIPHERAL                              LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_BT_UART_RXD_SIGNAL                             lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_BT_UART_RXD_CHANNEL                                   19U   /*!< Signal channel */

/* GPIO_DISP_B2_12 (coord B6), GPIO_DISP_B2_12 */
/* Routed pin properties */
#define BOARD_INITPINS_GPIO_DISP_B2_12_PERIPHERAL                          LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_GPIO_DISP_B2_12_SIGNAL                         lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_GPIO_DISP_B2_12_CHANNEL                               20U   /*!< Signal channel */

/* GPIO_DISP_B2_13 (coord A5), BT_UART_RTS */
/* Routed pin properties */
#define BOARD_INITPINS_BT_UART_RTS_PERIPHERAL                              LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_BT_UART_RTS_SIGNAL                             lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_BT_UART_RTS_CHANNEL                                   21U   /*!< Signal channel */

/* GPIO_DISP_B1_02 (coord D11), ENET_RGMII_RXD0 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RGMII_RXD0_PERIPHERAL                          LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RGMII_RXD0_SIGNAL                        lcdif_hsync   /*!< Signal name */

/* GPIO_DISP_B1_03 (coord E11), ENET_RGMII_RXD1 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RGMII_RXD1_PERIPHERAL                          LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RGMII_RXD1_SIGNAL                        lcdif_vsync   /*!< Signal name */

/* GPIO_AD_20 (coord K13), SAI1_RXD[0]/J9[7]/J50[20]/J61[1]/BT_PCM_RXD/U16[10]/U355[18] */
/* Routed pin properties */
#define BOARD_INITPINS_en_5v_PERIPHERAL                                    GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_en_5v_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_en_5v_CHANNEL                                         19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_en_5v_GPIO                                          GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_en_5v_GPIO_PIN                                        19U   /*!< GPIO pin number */
#define BOARD_INITPINS_en_5v_GPIO_PIN_MASK                           (1U << 19U)   /*!< GPIO pin mask */

/* GPIO_AD_16 (coord N17), SPDIF_OUT/WIFI_RST_B/U354[3] */
/* Routed pin properties */
#define BOARD_INITPINS_bklt_PERIPHERAL                                     GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_bklt_SIGNAL                                       gpio_io   /*!< Signal name */
#define BOARD_INITPINS_bklt_CHANNEL                                          15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_bklt_GPIO                                           GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_bklt_GPIO_PIN                                         15U   /*!< GPIO pin number */
#define BOARD_INITPINS_bklt_GPIO_PIN_MASK                            (1U << 15U)   /*!< GPIO pin mask */

/* GPIO_AD_15 (coord M14), SPDIF_IN/U43[4]/BT_RST#/U16[14]/J54[54] */
/* Routed pin properties */
#define BOARD_INITPINS_tft_3v3_PERIPHERAL                                  GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_tft_3v3_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_tft_3v3_CHANNEL                                       14U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_tft_3v3_GPIO                                        GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_tft_3v3_GPIO_PIN                                      14U   /*!< GPIO pin number */
#define BOARD_INITPINS_tft_3v3_GPIO_PIN_MASK                         (1U << 14U)   /*!< GPIO pin mask */

/* GPIO_AD_04 (coord M13), SIM1_PD/J44[C8]/USER_LED_CTL1/J9[8]/J25[7] */
/* Routed pin properties */
#define BOARD_INITPINS_batt_sw_PERIPHERAL                                  GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_batt_sw_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_batt_sw_CHANNEL                                        3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_batt_sw_GPIO                                        GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_batt_sw_GPIO_PIN                                       3U   /*!< GPIO pin number */
#define BOARD_INITPINS_batt_sw_GPIO_PIN_MASK                          (1U << 3U)   /*!< GPIO pin mask */

/* GPIO_AD_28 (coord L17), LPSPI1_SCK/U27[6]/BT_DEV_WAKE/U354[9]/U16[39]/J10[12] */
/* Routed pin properties */
#define BOARD_INITPINS_batt_en_PERIPHERAL                                  GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_batt_en_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_batt_en_CHANNEL                                       27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_batt_en_GPIO                                        GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_batt_en_GPIO_PIN                                      27U   /*!< GPIO pin number */
#define BOARD_INITPINS_batt_en_GPIO_PIN_MASK                         (1U << 27U)   /*!< GPIO pin mask */

/* GPIO_AD_02 (coord R13), SIM1_RST/J57[5]/J44[C2]/LCD_RST_B/J48[21]/J25[11]/J10[6] */
/* Routed pin properties */
#define BOARD_INITPINS_tft_xres_PERIPHERAL                                 GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_tft_xres_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_tft_xres_CHANNEL                                       1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_tft_xres_GPIO                                       GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_tft_xres_GPIO_PIN                                      1U   /*!< GPIO pin number */
#define BOARD_INITPINS_tft_xres_GPIO_PIN_MASK                         (1U << 1U)   /*!< GPIO pin mask */

/* GPIO_DISP_B1_01 (coord D13), ENET_RGMII_RXC/U10[27] */
/* Routed pin properties */
#define BOARD_INITPINS_tft_csb_PERIPHERAL                                 GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_tft_csb_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_tft_csb_CHANNEL                                       22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_tft_csb_GPIO                                       GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_tft_csb_GPIO_PIN                                      22U   /*!< GPIO pin number */
#define BOARD_INITPINS_tft_csb_GPIO_PIN_MASK                         (1U << 22U)   /*!< GPIO pin mask */

/* GPIO_AD_14 (coord N14), SPDIF_EXT_CLK/CAN_STBY/J9[16] */
/* Routed pin properties */
#define BOARD_INITPINS_CAN_STB_PERIPHERAL                                  GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_CAN_STB_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_CAN_STB_CHANNEL                                       13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CAN_STB_GPIO                                        GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_CAN_STB_GPIO_PIN                                      13U   /*!< GPIO pin number */
#define BOARD_INITPINS_CAN_STB_GPIO_PIN_MASK                         (1U << 13U)   /*!< GPIO pin mask */

/* GPIO_LPSR_00 (coord N6), CAN3_TX */
/* Routed pin properties */
#define BOARD_INITPINS_CAN3_TX_PERIPHERAL                                   CAN3   /*!< Peripheral name */
#define BOARD_INITPINS_CAN3_TX_SIGNAL                                         TX   /*!< Signal name */

/* GPIO_LPSR_01 (coord R6), CAN3_RX */
/* Routed pin properties */
#define BOARD_INITPINS_CAN3_RX_PERIPHERAL                                   CAN3   /*!< Peripheral name */
#define BOARD_INITPINS_CAN3_RX_SIGNAL                                         RX   /*!< Signal name */

/* GPIO_AD_19 (coord L16), SAI1_RX_BCLK/J9[1]/J50[18]/U32[12] */
/* Routed pin properties */
#define BOARD_INITPINS_ABS_PERIPHERAL                                      GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_ABS_SIGNAL                                        gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ABS_CHANNEL                                           18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ABS_GPIO                                            GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ABS_GPIO_PIN                                          18U   /*!< GPIO pin number */
#define BOARD_INITPINS_ABS_GPIO_PIN_MASK                             (1U << 18U)   /*!< GPIO pin mask */

/* GPIO_AD_11 (coord P16), USB_OTG1_OC/U26[A2]/J26[4] */
/* Routed pin properties */
#define BOARD_INITPINS_AI_SBATTFUEL_MON_MCU_IN_PERIPHERAL                 LPADC1   /*!< Peripheral name */
#define BOARD_INITPINS_AI_SBATTFUEL_MON_MCU_IN_SIGNAL                          B   /*!< Signal name */
#define BOARD_INITPINS_AI_SBATTFUEL_MON_MCU_IN_CHANNEL                        1U   /*!< Signal channel */

/* GPIO_EMC_B2_20 (coord R3), ENET_RGMII_MDIO */
/* Routed pin properties */
#define BOARD_INITPINS_FUEL_SBATT_CTRL_MCUOUT_PERIPHERAL                   GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_FUEL_SBATT_CTRL_MCUOUT_SIGNAL                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_FUEL_SBATT_CTRL_MCUOUT_CHANNEL                        30U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_FUEL_SBATT_CTRL_MCUOUT_GPIO                         GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_FUEL_SBATT_CTRL_MCUOUT_GPIO_PIN                       30U   /*!< GPIO pin number */
#define BOARD_INITPINS_FUEL_SBATT_CTRL_MCUOUT_GPIO_PIN_MASK          (1U << 30U)   /*!< GPIO pin mask */

/* GPIO_AD_09 (coord R16), USB_OTG1_ID/U28[3]/U26[A1]/J26[10]/J20[4] */
/* Routed pin properties */
#define BOARD_INITPINS_AI_FUEL_MCU_IN_PERIPHERAL                          LPADC1   /*!< Peripheral name */
#define BOARD_INITPINS_AI_FUEL_MCU_IN_SIGNAL                                   B   /*!< Signal name */
#define BOARD_INITPINS_AI_FUEL_MCU_IN_CHANNEL                                 1U   /*!< Signal channel */

/* GPIO_AD_10 (coord R17), USB_OTG1_PWR/J26[2]/U26[A1] */
/* Routed pin properties */
#define BOARD_INITPINS_SBAT_PERIPHERAL                                    LPADC1   /*!< Peripheral name */
#define BOARD_INITPINS_SBAT_SIGNAL                                             A   /*!< Signal name */
#define BOARD_INITPINS_SBAT_CHANNEL                                           1U   /*!< Signal channel */

/* GPIO_EMC_B2_19 (coord U2), ENET_RGMII_MDC */
/* Routed pin properties */
#define BOARD_INITPINS_DO_BATT_MON_EN_PERIPHERAL                           GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_DO_BATT_MON_EN_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DO_BATT_MON_EN_CHANNEL                                29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DO_BATT_MON_EN_GPIO                                 GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DO_BATT_MON_EN_GPIO_PIN                               29U   /*!< GPIO pin number */
#define BOARD_INITPINS_DO_BATT_MON_EN_GPIO_PIN_MASK                  (1U << 29U)   /*!< GPIO pin mask */

/* GPIO_SD_B1_02 (coord C15), LOW_OIL */
/* Routed pin properties */
#define BOARD_INITPINS_DI_LOW_OIL_PRESSURE_MCU_IN_PERIPHERAL              GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_DI_LOW_OIL_PRESSURE_MCU_IN_SIGNAL                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_LOW_OIL_PRESSURE_MCU_IN_CHANNEL                     5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_LOW_OIL_PRESSURE_MCU_IN_GPIO                    GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_LOW_OIL_PRESSURE_MCU_IN_GPIO_PIN                    5U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_LOW_OIL_PRESSURE_MCU_IN_GPIO_PIN_MASK       (1U << 5U)   /*!< GPIO pin mask */

/* GPIO_LPSR_04 (coord N7), I2C5_SDA/J48[26]/U32[18]/U34[6]/J10[18] */
/* Routed pin properties */
#define BOARD_INITPINS_EEPROM_I2C_SDA_PERIPHERAL                          LPI2C5   /*!< Peripheral name */
#define BOARD_INITPINS_EEPROM_I2C_SDA_SIGNAL                                 SDA   /*!< Signal name */

/* GPIO_LPSR_05 (coord N8), I2C5_SCL/J48[27]/U32[17]/U34[4]/J10[20] */
/* Routed pin properties */
#define BOARD_INITPINS_EEPROM_I2C_SCL_PERIPHERAL                          LPI2C5   /*!< Peripheral name */
#define BOARD_INITPINS_EEPROM_I2C_SCL_SIGNAL                                 SCL   /*!< Signal name */

/* WAKEUP (coord T8), DI_IGN_MCU_IN */
/* Routed pin properties */
#define BOARD_INITPINS_DI_IGN_MCU_IN_PERIPHERAL                           GPIO13   /*!< Peripheral name */
#define BOARD_INITPINS_DI_IGN_MCU_IN_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_IGN_MCU_IN_CHANNEL                                  0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_IGN_MCU_IN_GPIO                                 GPIO13   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_IGN_MCU_IN_GPIO_PIN                                 0U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_IGN_MCU_IN_GPIO_PIN_MASK                    (1U << 0U)   /*!< GPIO pin mask */

/* GPIO_SD_B1_03 (coord B17), SD1_D1/J15[8]/WIFI_SDIO_D1/J54[15] */
/* Routed pin properties */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_SET_MCU_IN_PERIPHERAL              GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_SET_MCU_IN_SIGNAL                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_SET_MCU_IN_CHANNEL                     6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_SET_MCU_IN_GPIO                    GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_SET_MCU_IN_GPIO_PIN                    6U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_SET_MCU_IN_GPIO_PIN_MASK       (1U << 6U)   /*!< GPIO pin mask */

/* DCDC_PSWITCH (coord P3), MCU_DCDC_IN/VDD_3V3 */
/* Routed pin properties */
#define BOARD_INITPINS_DCDC_PSWITCH_PERIPHERAL                            SUPPLY   /*!< Peripheral name */
#define BOARD_INITPINS_DCDC_PSWITCH_SIGNAL                          dcdc_pswitch   /*!< Signal name */

/* GPIO_EMC_B1_14 (coord B1), SEMC_A5 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A5_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A5_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A5_CHANNEL                                       14U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_A5_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_A5_GPIO_PIN                                      14U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_A5_GPIO_PIN_MASK                         (1U << 14U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_15 (coord C1), SEMC_A6 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A6_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A6_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A6_CHANNEL                                       15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_A6_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_A6_GPIO_PIN                                      15U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_A6_GPIO_PIN_MASK                         (1U << 15U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_32 (coord D1), SEMC_D10 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D10_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D10_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D10_CHANNEL                                       0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D10_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D10_GPIO_PIN                                      0U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D10_GPIO_PIN_MASK                         (1U << 0U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_34 (coord E1), SEMC_D12 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D12_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D12_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D12_CHANNEL                                       2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D12_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D12_GPIO_PIN                                      2U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D12_GPIO_PIN_MASK                         (1U << 2U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_35 (coord F1), SEMC_D13 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D13_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D13_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D13_CHANNEL                                       3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D13_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D13_GPIO_PIN                                      3U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D13_GPIO_PIN_MASK                         (1U << 3U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_36 (coord G1), SEMC_D14 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D14_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D14_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D14_CHANNEL                                       4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D14_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D14_GPIO_PIN                                      4U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D14_GPIO_PIN_MASK                         (1U << 4U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_37 (coord H1), SEMC_D15/U13[53] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D15_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D15_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D15_CHANNEL                                       5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D15_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D15_GPIO_PIN                                      5U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D15_GPIO_PIN_MASK                         (1U << 5U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_38 (coord J1), SEMC_DM1 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_DM1_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_DM1_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_DM1_CHANNEL                                       6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_DM1_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_DM1_GPIO_PIN                                      6U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_DM1_GPIO_PIN_MASK                         (1U << 6U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_40 (coord K1), SEMC_RDY */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_RDY_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_RDY_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_RDY_CHANNEL                                       8U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_RDY_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_RDY_GPIO_PIN                                      8U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_RDY_GPIO_PIN_MASK                         (1U << 8U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_41 (coord L1), SEMC_CSX0 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_CSX0_PERIPHERAL                                GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_CSX0_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_CSX0_CHANNEL                                      9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_CSX0_GPIO                                      GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_CSX0_GPIO_PIN                                     9U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_CSX0_GPIO_PIN_MASK                        (1U << 9U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_04 (coord M1), SEMC_D20 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D20_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D20_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D20_CHANNEL                                      14U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D20_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D20_GPIO_PIN                                     14U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D20_GPIO_PIN_MASK                        (1U << 14U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_05 (coord N1), SEMC_D21 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D21_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D21_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D21_CHANNEL                                      15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D21_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D21_GPIO_PIN                                     15U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D21_GPIO_PIN_MASK                        (1U << 15U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_08 (coord P1), SEMC_DM2 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_DM2_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_DM2_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_DM2_CHANNEL                                      18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_DM2_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_DM2_GPIO_PIN                                     18U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_DM2_GPIO_PIN_MASK                        (1U << 18U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_03 (coord R1), SEMC_D19 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D19_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D19_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D19_CHANNEL                                      13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D19_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D19_GPIO_PIN                                     13U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D19_GPIO_PIN_MASK                        (1U << 13U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_06 (coord T1), SEMC_D22 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D22_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D22_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D22_CHANNEL                                      16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D22_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D22_GPIO_PIN                                     16U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D22_GPIO_PIN_MASK                        (1U << 16U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_10 (coord A2), SEMC_A1 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A1_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A1_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A1_CHANNEL                                       10U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_A1_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_A1_GPIO_PIN                                      10U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_A1_GPIO_PIN_MASK                         (1U << 10U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_23 (coord B2), SEMC_A10 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A10_PERIPHERAL                                 GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A10_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A10_CHANNEL                                      23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_A10_GPIO                                       GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_A10_GPIO_PIN                                     23U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_A10_GPIO_PIN_MASK                        (1U << 23U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_11 (coord C2), SEMC_A2 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A2_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A2_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A2_CHANNEL                                       11U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_A2_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_A2_GPIO_PIN                                      11U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_A2_GPIO_PIN_MASK                         (1U << 11U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_31 (coord D2), SEMC_D9 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D9_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D9_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D9_CHANNEL                                       31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D9_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D9_GPIO_PIN                                      31U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D9_GPIO_PIN_MASK                         (1U << 31U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_33 (coord E2), SEMC_D11 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D11_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D11_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D11_CHANNEL                                       1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D11_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D11_GPIO_PIN                                      1U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D11_GPIO_PIN_MASK                         (1U << 1U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_01 (coord F2), SEMC_D1 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D1_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D1_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D1_CHANNEL                                        1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D1_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D1_GPIO_PIN                                       1U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D1_GPIO_PIN_MASK                          (1U << 1U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_21 (coord G2), SEMC_BA0 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_BA0_PERIPHERAL                                 GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_BA0_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_BA0_CHANNEL                                      21U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_BA0_GPIO                                       GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_BA0_GPIO_PIN                                     21U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_BA0_GPIO_PIN_MASK                        (1U << 21U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_22 (coord H2), SEMC_BA1 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_BA1_PERIPHERAL                                 GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_BA1_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_BA1_CHANNEL                                      22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_BA1_GPIO                                       GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_BA1_GPIO_PIN                                     22U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_BA1_GPIO_PIN_MASK                        (1U << 22U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_39 (coord J2), SEMC_DQS */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_DQS_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_DQS_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_DQS_CHANNEL                                       7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_DQS_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_DQS_GPIO_PIN                                      7U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_DQS_GPIO_PIN_MASK                         (1U << 7U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_00 (coord K2), SEMC_D16 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D16_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D16_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D16_CHANNEL                                      10U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D16_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D16_GPIO_PIN                                     10U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D16_GPIO_PIN_MASK                        (1U << 10U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_15 (coord L2), SEMC_D30 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D30_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D30_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D30_CHANNEL                                      25U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D30_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D30_GPIO_PIN                                     25U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D30_GPIO_PIN_MASK                        (1U << 25U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_12 (coord M2), SEMC_D27 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D27_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D27_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D27_CHANNEL                                      22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D27_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D27_GPIO_PIN                                     22U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D27_GPIO_PIN_MASK                        (1U << 22U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_09 (coord N2), SEMC_D24 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D24_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D24_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D24_CHANNEL                                      19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D24_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D24_GPIO_PIN                                     19U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D24_GPIO_PIN_MASK                        (1U << 19U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_16 (coord P2), SEMC_D21 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D31_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D31_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D31_CHANNEL                                      26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D31_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D31_GPIO_PIN                                     26U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D31_GPIO_PIN_MASK                        (1U << 26U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_10 (coord R2), SEMC_D25 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D25_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D25_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D25_CHANNEL                                      20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D25_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D25_GPIO_PIN                                     20U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D25_GPIO_PIN_MASK                        (1U << 20U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_17 (coord T2), SEMC_DM3 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_DM3_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_DM3_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_DM3_CHANNEL                                      27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_DM3_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_DM3_GPIO_PIN                                     27U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_DM3_GPIO_PIN_MASK                        (1U << 27U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_09 (coord A3), SEMC_A0 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A0_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A0_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A0_CHANNEL                                        9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_A0_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_A0_GPIO_PIN                                       9U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_A0_GPIO_PIN_MASK                          (1U << 9U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_17 (coord B3), SEMC_A8 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A8_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A8_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A8_CHANNEL                                       17U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_A8_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_A8_GPIO_PIN                                      17U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_A8_GPIO_PIN_MASK                         (1U << 17U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_20 (coord C3), SEMC_A12 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A12_PERIPHERAL                                 GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A12_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A12_CHANNEL                                      20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_A12_GPIO                                       GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_A12_GPIO_PIN                                     20U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_A12_GPIO_PIN_MASK                        (1U << 20U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_16 (coord D3), SEMC_A7 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A7_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A7_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A7_CHANNEL                                       16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_A7_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_A7_GPIO_PIN                                      16U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_A7_GPIO_PIN_MASK                         (1U << 16U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_30 (coord E3), SEMC_D8 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D8_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D8_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D8_CHANNEL                                       30U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D8_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D8_GPIO_PIN                                      30U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D8_GPIO_PIN_MASK                         (1U << 30U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_00 (coord F3), SEMC_D0 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D0_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D0_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D0_CHANNEL                                        0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D0_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D0_GPIO_PIN                                       0U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D0_GPIO_PIN_MASK                          (1U << 0U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_07 (coord H3), SEMC_D7 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D7_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D7_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D7_CHANNEL                                        7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D7_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D7_GPIO_PIN                                       7U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D7_GPIO_PIN_MASK                          (1U << 7U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_26 (coord J3), SEMC_CLK */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_CLK_PERIPHERAL                                 GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_CLK_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_CLK_CHANNEL                                      26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_CLK_GPIO                                       GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_CLK_GPIO_PIN                                     26U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_CLK_GPIO_PIN_MASK                        (1U << 26U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_02 (coord K3), SEMC_D18 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D18_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D18_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D18_CHANNEL                                      12U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D18_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D18_GPIO_PIN                                     12U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D18_GPIO_PIN_MASK                        (1U << 12U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_07 (coord M3), SEMC_D23 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D23_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D23_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D23_CHANNEL                                      17U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D23_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D23_GPIO_PIN                                     17U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D23_GPIO_PIN_MASK                        (1U << 17U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_18 (coord N3), SEMC_DQS4 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_DQS4_PERIPHERAL                                GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_DQS4_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_DQS4_CHANNEL                                     28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_DQS4_GPIO                                      GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_DQS4_GPIO_PIN                                    28U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_DQS4_GPIO_PIN_MASK                       (1U << 28U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_18 (coord B4), SEMC_A9 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A9_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A9_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A9_CHANNEL                                       18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_A9_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_A9_GPIO_PIN                                      18U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_A9_GPIO_PIN_MASK                         (1U << 18U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_19 (coord C4), SEMC_A11 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A11_PERIPHERAL                                 GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A11_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A11_CHANNEL                                      19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_A11_GPIO                                       GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_A11_GPIO_PIN                                     19U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_A11_GPIO_PIN_MASK                        (1U << 19U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_03 (coord E4), SEMC_D3 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D3_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D3_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D3_CHANNEL                                        3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D3_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D3_GPIO_PIN                                       3U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D3_GPIO_PIN_MASK                          (1U << 3U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_05 (coord F4), SEMC_D5 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D5_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D5_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D5_CHANNEL                                        5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D5_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D5_GPIO_PIN                                       5U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D5_GPIO_PIN_MASK                          (1U << 5U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_02 (coord G4), SEMC_D2 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D2_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D2_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D2_CHANNEL                                        2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D2_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D2_GPIO_PIN                                       2U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D2_GPIO_PIN_MASK                          (1U << 2U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_06 (coord H4), SEMC_D6 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D6_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D6_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D6_CHANNEL                                        6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D6_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D6_GPIO_PIN                                       6U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D6_GPIO_PIN_MASK                          (1U << 6U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_25 (coord J4), SEMC_RAS */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_RAS_PERIPHERAL                                 GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_RAS_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_RAS_CHANNEL                                      25U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_RAS_GPIO                                       GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_RAS_GPIO_PIN                                     25U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_RAS_GPIO_PIN_MASK                        (1U << 25U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_01 (coord K4), SEMC_D17 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D17_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D17_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D17_CHANNEL                                      11U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D17_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D17_GPIO_PIN                                     11U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D17_GPIO_PIN_MASK                        (1U << 11U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_11 (coord L4), SEMC_D26 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D26_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D26_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D26_CHANNEL                                      21U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D26_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D26_GPIO_PIN                                     21U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D26_GPIO_PIN_MASK                        (1U << 21U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_14 (coord M4), SEMC_D29 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D29_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D29_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D29_CHANNEL                                      24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D29_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D29_GPIO_PIN                                     24U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D29_GPIO_PIN_MASK                        (1U << 24U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_12 (coord C5), SEMC_A3 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A3_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A3_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A3_CHANNEL                                       12U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_A3_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_A3_GPIO_PIN                                      12U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_A3_GPIO_PIN_MASK                         (1U << 12U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_13 (coord D5), SEMC_A4 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_A4_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_A4_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_A4_CHANNEL                                       13U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_A4_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_A4_GPIO_PIN                                      13U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_A4_GPIO_PIN_MASK                         (1U << 13U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_28 (coord E5), SEMC_WE */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_WE_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_WE_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_WE_CHANNEL                                       28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_WE_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_WE_GPIO_PIN                                      28U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_WE_GPIO_PIN_MASK                         (1U << 28U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_08 (coord F5), SEMC_DM0 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_DM0_PERIPHERAL                                 GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_DM0_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_DM0_CHANNEL                                       8U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_DM0_GPIO                                       GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_DM0_GPIO_PIN                                      8U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_DM0_GPIO_PIN_MASK                         (1U << 8U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_27 (coord G5), SEMC_CKE */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_CKE_PERIPHERAL                                 GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_CKE_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_CKE_CHANNEL                                      27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_CKE_GPIO                                       GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_CKE_GPIO_PIN                                     27U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_CKE_GPIO_PIN_MASK                        (1U << 27U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_04 (coord H5), SEMC_D4 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D4_PERIPHERAL                                  GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D4_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D4_CHANNEL                                        4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D4_GPIO                                        GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D4_GPIO_PIN                                       4U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D4_GPIO_PIN_MASK                          (1U << 4U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_24 (coord J5), SEMC_CAS */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_CAS_PERIPHERAL                                 GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_CAS_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_CAS_CHANNEL                                      24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_CAS_GPIO                                       GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_CAS_GPIO_PIN                                     24U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_CAS_GPIO_PIN_MASK                        (1U << 24U)   /*!< GPIO pin mask */

/* GPIO_EMC_B2_13 (coord K5), SEMC_D28 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D28_PERIPHERAL                                 GPIO8   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D28_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D28_CHANNEL                                      23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D28_GPIO                                       GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D28_GPIO_PIN                                     23U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D28_GPIO_PIN_MASK                        (1U << 23U)   /*!< GPIO pin mask */

/* GPIO_EMC_B1_29 (coord E6), SEMC_CS0 */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_CS0_PERIPHERAL                                 GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_CS0_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_CS0_CHANNEL                                      29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_CS0_GPIO                                       GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_CS0_GPIO_PIN                                     29U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_CS0_GPIO_PIN_MASK                        (1U << 29U)   /*!< GPIO pin mask */

/* PMIC_ON_REQ (coord U9), PMIC_ON_REQ */
/* Routed pin properties */
#define BOARD_INITPINS_PMIC_ON_REQ_PERIPHERAL                               SNVS   /*!< Peripheral name */
#define BOARD_INITPINS_PMIC_ON_REQ_SIGNAL                    snvs_lp_pmic_on_req   /*!< Signal name */

/* GPIO_AD_03 (coord P15), SIM1_SVEN/J57[2]/Flash_RST/U21[B2]/J25[9]/J10[8] */
/* Routed pin properties */
#define BOARD_INITPINS_FOG_LAMP_PERIPHERAL                                 GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_FOG_LAMP_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_FOG_LAMP_CHANNEL                                       2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_FOG_LAMP_GPIO                                       GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_FOG_LAMP_GPIO_PIN                                      2U   /*!< GPIO pin number */
#define BOARD_INITPINS_FOG_LAMP_GPIO_PIN_MASK                         (1U << 2U)   /*!< GPIO pin mask */

/* GPIO_SD_B1_04 (coord B15), SD1_D2/J15[1]/WIFI_SDIO_D2/J54[17] */
/* Routed pin properties */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_RETURN_MCU_IN_PERIPHERAL           GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_RETURN_MCU_IN_SIGNAL              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_RETURN_MCU_IN_CHANNEL                  7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_RETURN_MCU_IN_GPIO                 GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_RETURN_MCU_IN_GPIO_PIN                 7U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_RETURN_MCU_IN_GPIO_PIN_MASK    (1U << 7U)   /*!< GPIO pin mask */

/* GPIO_SD_B1_01 (coord D15), SD1_CLK/J15[5]/WIFI_SDIO_CLK/J54[9] */
/* Routed pin properties */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_DOWN_MCU_IN_PERIPHERAL             GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_DOWN_MCU_IN_SIGNAL                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_DOWN_MCU_IN_CHANNEL                    4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_DOWN_MCU_IN_GPIO                   GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_DOWN_MCU_IN_GPIO_PIN                   4U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_DOWN_MCU_IN_GPIO_PIN_MASK      (1U << 4U)   /*!< GPIO pin mask */

/* GPIO_SD_B1_05 (coord A16), SD1_D3/J15[2]/WIFI_SDIO_D3/J54[19] */
/* Routed pin properties */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_UP_MCU_IN_PERIPHERAL               GPIO10   /*!< Peripheral name */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_UP_MCU_IN_SIGNAL                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_UP_MCU_IN_CHANNEL                      8U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_UP_MCU_IN_GPIO                     GPIO10   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_UP_MCU_IN_GPIO_PIN                     8U   /*!< GPIO pin number */
#define BOARD_INITPINS_DI_HANDLEBAR_SW_UP_MCU_IN_GPIO_PIN_MASK        (1U << 8U)   /*!< GPIO pin mask */

/* GPIO_AD_23 (coord J12), BT_PCM_SYNC */
/* Routed pin properties */
#define BOARD_INITPINS_BT_PCM_SYNC_PERIPHERAL                              GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_BT_PCM_SYNC_SIGNAL                            gpio_mux_io   /*!< Signal name */
#define BOARD_INITPINS_BT_PCM_SYNC_CHANNEL                                   22U   /*!< Signal channel */

/* GPIO_AD_13 (coord L12), SPDIF_SR_CLK/ANATOP_32K_OUT/J26[8] */
/* Routed pin properties */
#define BOARD_INITPINS_TT_SS_DIG_MCU_OUT_PERIPHERAL                        GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_TT_SS_DIG_MCU_OUT_SIGNAL                          gpio_io   /*!< Signal name */
#define BOARD_INITPINS_TT_SS_DIG_MCU_OUT_CHANNEL                             12U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_TT_SS_DIG_MCU_OUT_GPIO                              GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_TT_SS_DIG_MCU_OUT_GPIO_PIN                            12U   /*!< GPIO pin number */
#define BOARD_INITPINS_TT_SS_DIG_MCU_OUT_GPIO_PIN_MASK               (1U << 12U)   /*!< GPIO pin mask */

/* GPIO_AD_18 (coord M16), SAI1_RX_SYNC/J9[5]/J50[19]/U32[13] */
/* Routed pin properties */
#define BOARD_INITPINS_AI_SSTT_FDBK_DIAG_PERIPHERAL                       LPADC2   /*!< Peripheral name */
#define BOARD_INITPINS_AI_SSTT_FDBK_DIAG_SIGNAL                                A   /*!< Signal name */
#define BOARD_INITPINS_AI_SSTT_FDBK_DIAG_CHANNEL                              2U   /*!< Signal channel */

/* GPIO_AD_00 (coord N12), SIM1_TRXD/J44[C7]/J57[9]/CTP_INT/J48[29]/J25[15]/J9[14] */
/* Routed pin properties */
#define BOARD_INITPINS_Illum_PWM_PERIPHERAL                                 PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_Illum_PWM_SIGNAL                                        A   /*!< Signal name */
#define BOARD_INITPINS_Illum_PWM_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_AD_32 (coord K16), ENET_MDC/U7[12]/SD1_CD_B/J15[9] */
/* Routed pin properties */
#define BOARD_INITPINS_BTLE_UART_TX_PERIPHERAL                          LPUART10   /*!< Peripheral name */
#define BOARD_INITPINS_BTLE_UART_TX_SIGNAL                                   TXD   /*!< Signal name */

/* GPIO_AD_33 (coord H17), ENET_MDIO/U7[11] */
/* Routed pin properties */
#define BOARD_INITPINS_BTLE_UART_RX_PERIPHERAL                          LPUART10   /*!< Peripheral name */
#define BOARD_INITPINS_BTLE_UART_RX_SIGNAL                                   RXD   /*!< Signal name */

/* GPIO_LPSR_08 (coord U8), DMIC_CLK/U41[1]/U44[1]/J50[18] */
/* Routed pin properties */
#define BOARD_INITPINS_DOUT_BTLE_PS_RST_PERIPHERAL                        GPIO12   /*!< Peripheral name */
#define BOARD_INITPINS_DOUT_BTLE_PS_RST_SIGNAL                           gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DOUT_BTLE_PS_RST_CHANNEL                               8U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DOUT_BTLE_PS_RST_GPIO                              GPIO12   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DOUT_BTLE_PS_RST_GPIO_PIN                              8U   /*!< GPIO pin number */
#define BOARD_INITPINS_DOUT_BTLE_PS_RST_GPIO_PIN_MASK                 (1U << 8U)   /*!< GPIO pin mask */

/* GPIO_AD_17 (coord N15), SAI1_MCLK/U32[11]/J9[15] */
/* Routed pin properties */
#define BOARD_INITPINS_BLE_3P3V_EN_PERIPHERAL                              GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_BLE_3P3V_EN_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BLE_3P3V_EN_CHANNEL                                   16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BLE_3P3V_EN_GPIO                                    GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BLE_3P3V_EN_GPIO_PIN                                  16U   /*!< GPIO pin number */
#define BOARD_INITPINS_BLE_3P3V_EN_GPIO_PIN_MASK                     (1U << 16U)   /*!< GPIO pin mask */

/* GPIO_LPSR_06 (coord P8), I2C6_SDA */
/* Routed pin properties */
#define BOARD_INITPINS_I2C6_SDA_PERIPHERAL                                LPI2C6   /*!< Peripheral name */
#define BOARD_INITPINS_I2C6_SDA_SIGNAL                                       SDA   /*!< Signal name */

/* GPIO_LPSR_07 (coord R8), I2C6_SCL */
/* Routed pin properties */
#define BOARD_INITPINS_I2C6_SCL_PERIPHERAL                                LPI2C6   /*!< Peripheral name */
#define BOARD_INITPINS_I2C6_SCL_SIGNAL                                       SCL   /*!< Signal name */

/* GPIO_AD_30 (coord K17), LPSPI1_SDO */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_SDO_PERIPHERAL                                CAN2   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_SDO_SIGNAL                                      TX   /*!< Signal name */

/* GPIO_AD_31 (coord J17), LPSPI1_SDI */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_SDI_PERIPHERAL                                CAN2   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_SDI_SIGNAL                                      RX   /*!< Signal name */

/* GPIO_AD_29 (coord M17), LPSP1_PCS0 */
/* Routed pin properties */
#define BOARD_INITPINS_LPSPI1_PCS0_PERIPHERAL                              GPIO9   /*!< Peripheral name */
#define BOARD_INITPINS_LPSPI1_PCS0_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LPSPI1_PCS0_CHANNEL                                   28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LPSPI1_PCS0_GPIO                                    GPIO9   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LPSPI1_PCS0_GPIO_PIN                                  28U   /*!< GPIO pin number */
#define BOARD_INITPINS_LPSPI1_PCS0_GPIO_PIN_MASK                     (1U << 28U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
